version: '3'

tasks:
  default:
    cmds:
      - task run
    silent: true
  run:
    cmds:
      - go build -o badger-cli .
      - ./badger-cli -p password16bits00 withpass.db
    silent: true
  nopass:
    cmds:
      - go build -o badger-cli .
      - ./badger-cli nopass.db
    silent: true
